### ISSUE TITLE
Provide an extension convention for kernels

### ISSUE THREAD

**Issue by SpencerPark** [SpencerPark/jupyter-jvm-basekernel#19]
Following discussion in SpencerPark/IJava#61, in the api package we can outline the extension loading convention and interfaces for loading via the [ServiceLoader](https://docs.oracle.com/javase/8/docs/api/java/util/ServiceLoader.html). 

An interface like `JupyterExtension` would be implemented by the extension and the appropriate service linking META-INF file would need to be declared. The service loader would take care of the rest.

The api package would define the interface with lifecycle methods that kernels are expected to make use of. Potentially the basekernel would load such extensions. Also the gradle plugin could define (and implement) a convention for placing extension jars in an `ext` folder beside the kernel? It would then provide an extension install script as well. 

```
java/
  - kernel.json
  - ijava-1.3.0.jar
  - ext/
    - ext1/
      - ext1-1.0.0.jar
    - ext2.jar
```

#### TODO:

- [x] implement the extension loading convention (pending decisions on some of the questions below)
- [ ] finalize the `JupyterKernel` and `JupyterExtension` interfaces (if we need to support reloading, etc.)
- [ ] make sure everything we are confident in the stability and generality of everything left in the api module
- [ ] write up an example to get a feel for the developer experience we are imposing on extension authors

**Comment by SpencerPark** [comment]
This work has been happening on the [restructure branch](https://github.com/SpencerPark/jupyter-jvm-basekernel/tree/restructure). With this work, extensions should now be able to just depend on the `jupyter-jvm-api` package. This decouples them from any kernel implementation, protocol changes, event the basekernel itself.

An extension is a simple interface implementation that takes a `JupyterKernel` and gets a chance to register what ever it likes.

There are 3 main extension points:
1.  `renderer(): Renderer` - is the service responsible for computing rich displays. Extensions can register their own render hooks to add support for displaying things as images, widgets, html, other media, etc. Note: the classes don't have to be classes the extension owns, hooks can be for any classes the extension cna get a reference to.
2.  `comms(): CommManager` - implements the bidirectional `comm` communication layer between the kernel and the backend. Extensions can hook into their front-end counterpart with this api.
3.  `magics(): Magics` - language agnostic user functions. In IPython (and IJava) these are the `%magic_name arg1...` functions. The magics interface is not dependent on a certain syntax for the implementation, but rather just a registry of named functions that take string arguments.

Of course extensions also have access to the kernel instance so they are also free to `eval` some code, print/display to the kernel's `io()`, inspect the `history()` etc. Likewise they can inspect the `getLanguageInfo()`, `getKernelName()`, and `getKernelVersion()` if they need to know more about the environment they are being loaded into.

**Comment by SpencerPark** [comment]
What is still up in the air is how we should apply extensions dynamically. The well defined case is where the kernel directory (or somewhere else in the classpath) contains a handful of extension jars and when the kernel starts, it asks the service loader to load all extensions and it immediately applies them.

In IJava, it is common (even encouraged) to load dependencies at runtime. So naturally I would expect that loading a dependency that contains an extension would load that extension. Here should we reload the service loader? Should we unload and reload all extensions? Some extensions may have optional dependencies on libraries. If one of those optional dependencies are loaded after initialization, the extension should somehow be notified.

This also brings up the questions again, should we separate the kernel, extension, and user classloaders?

**Comment by SpencerPark** [comment]
Given this a lot of thought...

1.  **We will for sure stick with the service loader interface.** No need to reinvent this when the standard already has what we need. So just fully commit to this foundation without trying to abstract it away.

2.  Extensions are applied to kernels. Ignore the special case with IJava where the lines between the user space and the kernel are very blurry. The kernel's classpath shouldn't be changing randomly at runtime... the user space's classpath does but that should be isolated. **Extensions cannot be unloaded/reloaded. They should be loaded once right after the kernel starts and should not be loaded again.**

3.  **Extensions are distributed in their own folder ~~(or a zip?)~~ and should expect to be loaded with their own classloader (that is a child of the kernel's classloader).** In the case of IJava, if an extension needs more specialized kernel features, then cast the kernel to the concrete class/interface of that specific kernel. If an extension wants to add to the user-space, it can `eval` code in the kernel or use some method on `IJavaKernel` (for example).

    If an extension has it's own dependencies, this approach should keep them isolated from the user-space as well as other extensions. If multiple extensions need to share a classloader they can just go in the same folder but there are no guarantees in with order they are loaded in.

4.  **Extensions should compile against just the api if possible.** That will be provided at runtime and will be nice and portable across implementations. So we'll put the extension spi in the api module.

**Comment by suyashcjoshi** [comment]
sounds good Spencer, great to see you're back and looking forward to the code changes.
